# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure('2') do |config|
  config.vm.box = "generic/ubuntu2110"
  config.vm.synced_folder "./cyphonic", "/cyphonic", type: "sshfs"
  config.vm.boot_timeout = 600

  (1..60).each do |i|
    config.vm.define "client#{i}" do |host|
      host.vm.provider "kvm" do |vbox|
        vbox.name   = "client#{i}"
        vbox.memory = "1024"
      end
      host.vm.hostname = "client#{i}"
      host.vm.network :public_network, ip: "10.0.100.#{99+i}", :bridge => 'enp1s0', :dev => 'enp1s0'
      host.vm.provision :shell, :path => "provision/node.sh"
    end
  end
end
