apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - image: grafana/grafana:5.4.3
          imagePullPolicy: IfNotPresent
          name: grafana
          ports:
            - containerPort: 3000
              name: http
          volumeMounts:
            - name: nfs-pv-grafana
              mountPath: /var/lib/grafana
      volumes:
        - name: nfs-pv-grafana
          persistentVolumeClaim:
            claimName: nfs-pv-grafana
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 472

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-pv-grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  type: LoadBalancer
  externalIPs:
    - 192.168.11.120
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      nodePort: 30000
  selector:
    app: grafana
